### ISSUE TITLE
Support least-privilege in Cloud/Control-Plane proxy

### ISSUE THREAD

**Issue by clemenskol** [pixie-io/pixie#1228]
**Describe the Task**

We require running the control-plane using least-privilege: our k8s cluster actually enforces that all containers are run as non-root (only cloud components - we understand this is a difficult requirement for Vizier). This seems to be the case for all components except for the nginx proxy container.

This container was previously improved to enforce a minimal set of privileges, but that's not sufficient in our case: we are required to set `runAsNonRoot: true` to meet internal compliance requirements. This is currently not possible, because the way the nginx configuration and pod configs are written, because nginx is configured to start as root and then drop privileges.

**Subtasks**

The list of concrete tasks which must be done to complete this task:

- [ ] Update the nginx configuration to not drop privileges
- [ ] Update the nginx configuration to not be patched at boot (the default entrypoint seems to update some files, but the file will be read-only) or copy the entrypoint into a place where it is editable
- [ ] Change the container to be launched using a non-root user and group (uid/guid `65534` seems to work from experiments)
- [ ] Remove specifying the container capabilities as part of the pod description (dropping capabilities is not needed/possible if not running as root)
