### ISSUE TITLE
[Operator] Don't use `cluster.local` in requests to NATS

### ISSUE THREAD

**Issue by JamesMBartlett** [pixie-io/pixie#1581]
**Describe the Task**
The operator currently makes a request to NATS at the URL `<ip>.pl.pod.cluster.local`. This assumes that users' cluster domain is `cluster.local`. It can also cause problems when users' nodes have unorthodox DNS setups (see #1544). We should remove the `cluster.local` from the URL and rely on kubernetes DNS search paths. In other words, we should request `<ip>.pl.pod` instead. However, currently our certificates SANs include `*.pl.pod.cluster.local` and not `*.pl.pod`. So we need to update the certs before making this change.

**Subtasks**
- [ ] Update vizier certificate SANs to include `*.pl.pod`
- [ ] Release vizier to ensure clusters have the new certs
- [ ] Update operator to request from NATs at `*.pl.pod`

Side note: when vizier is deployed with `dev_cloud_namespace` it will connect to vzconn using a `cluster.local` address, so we can fix that as part of this issue too.

**Comment by vignesh-sc** [comment]
Hi @JamesMBartlett, Any updates on this issue ? Or are there any workarounds. I am having a similar issue when using a cusom domain with cloud dns and GKE.

**Comment by ddelnano** [comment]
I set up my own GKE cluster using Cloud DNS with a GKE cluster scope to perform some testing on this. I believe the solution that @JamesMBartlett outlined above will work for environments that use kube-dns, but unfortunately Cloud DNS or anything using [k8's external-dns](https://github.com/kubernetes-sigs/external-dns) won't.  The [external-dns FAQ](https://github.com/kubernetes-sigs/external-dns/blob/d7cec324d95fe2892d149a51307acefa3b7a37ee/docs/faq.md#which-kubernetes-objects-are-supported) states that only Services of the following type are supported (meaning Pod DNS records won't exist):

> Services exposed via type=LoadBalancer, type=ExternalName, type=NodePort, and for the hostnames defined in Ingress objects as well as [headless hostPort](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/hostport.md) services.

Therefore, the Cloud DNS controller doesn't create any records within the `pod.<cluster domain>` subdomain. It does appear to create IP records, but they are scoped within `<resource namespace>.svc.<cluster domain>`.

```
$ kubectl -n pl get pods -o wide
NAME                                     READY   STATUS             RESTARTS         AGE   IP               NODE                                                NOMINATED NODE   READINESS GATES
pl-nats-0                                0/1     Running            0                8s    10.145.240.158   gke-ddelnano-nr-168275-default-pool-3a1b8344-7171   <none>           <none>
```

<img width="1470" alt="Screenshot 2023-10-12 at 10 23 13 AM" src="https://github.com/pixie-io/pixie/assets/5855593/1b7ebc22-666f-4709-9081-e2f373657db9">

So the `pl-nats-mgmt` service will create corresponding svc records, but the pl-nats service won't. Where we generate the vizier SANs it seems that `pl-nats-mgmt` isn't referenced ([source](https://github.com/pixie-io/pixie/blob/3e02189116d9c3c5f488504894d015809d0bcf19/src/utils/shared/certs/certs.go#L118-L130)).

@JamesMBartlett what's the purpose for having both `pl-nats` and `pl-nats-mgmt`?  It seems the former is what the vizier components use and the latter is used in the init containers. If the operator can use the `pl-nats-mgmt` Service, than I think we could accommodate the external-dns use cases by trying `<ip>.pl-nats-mgmt` if the existing request is unsuccessful (`<ip>.pl.pod.<cluster subdomain>`).

**Comment by ddelnano** [comment]
In order to test this out, I have a very crude experiment that updates the vizier SANs to use the cluster domain rather than the hardcoded `cluster.local` and have updated the operator to use the `pl-nats-mgmt` and cloud connector service rather than the Pod DNS names only available from kubedns ([diff](https://github.com/pixie-io/pixie/compare/8bba1ad0ad83dab3bae0e7836847b9d017f0fa30...66836b1e783dd40b414e7401aafbd34a65f9ce3f), [branch](https://github.com/ddelnano/pixie/tree/ddelnano/experiment-to-fix-non-cluster-local-domain-clusters)).

I deployed the operator with skaffold and created a Vizier CRD by hand and verified that the vizier is created successfully. So this issue isn't limited to NATs. The cloud connector also has a similar problem, except it doesn't have a corresponding headless service that will return the A records of the Pod.

**Comment by JamesMBartlett** [comment]
> In order to test this out, I have a very crude experiment that updates the vizier SANs to use the cluster domain rather than the hardcoded `cluster.local` and have updated the operator to use the `pl-nats-mgmt` and cloud connector service rather than the Pod DNS names only available from kubedns ([diff](https://github.com/pixie-io/pixie/compare/8bba1ad0ad83dab3bae0e7836847b9d017f0fa30...66836b1e783dd40b414e7401aafbd34a65f9ce3f), [branch](https://github.com/ddelnano/pixie/tree/ddelnano/experiment-to-fix-non-cluster-local-domain-clusters)).
> 
> I deployed the operator with skaffold and created a Vizier CRD by hand and verified that the vizier is created successfully. So this issue isn't limited to NATs. The cloud connector also has a similar problem, except it doesn't have a corresponding headless service that will return the A records of the Pod.

That diff looks reasonable to me. 

I don't immediately see any issue with using the SvcPodAddr for `pl-nats-mgmt` instead of the nats pod directly.

As far as the purpose of both `pl-nats` and `pl-nats-mgmt`, I can't quite remember why we did that. @vihangm or @aimichelle  might have more context on that decision.

**Comment by rkuklins** [comment]
Hi all, any progress on this topic?

**Comment by ddelnano** [comment]
Hey @rkuklins, I don't have access to a GKE cluster anymore, so I'm not able to easily test and clean up my change from above. If you have interest in attempting address this, I'm happy to help through the implementation of that.
