### ISSUE TITLE
Migrate from STAN to Jetstream

### ISSUE THREAD

**Issue by zasgar** [pixie-io/pixie#531]
**Describe the Task**
Stan is deprecated. We should migrate the pixie control plane to be on Jetstream instead of Stan. 

**Subtasks**
- [x] Enable JetStream in NATS
- [x] Validate JetStream feature parity with STAN
- [x] Switch consumers to JetStream
- [x] Remove STAN

**Comment by vihangm** [comment]
This has been completed and we have switched over to JetStream.
