### ISSUE TITLE
Investigate addresses from /proc/<pid>/maps::[uprobes] in stack traces.

### ISSUE THREAD

**Issue by etep** [pixie-io/pixie#544]
**Describe the Task**
We noticed addresses from `[uprobes]`, a memory region shown in `/proc/<pid>/maps` in some stack traces. We have determined that the go uprobe for `casgstatus` is responsible for this stack trace, but we do not know why we see this address in stack traces, nor do we know if there is some additional perf impact for this probe.

<img width="506" alt="Screen Shot 2022-07-25 at 3 02 29 PM" src="https://user-images.githubusercontent.com/809015/180881904-9d6fd1be-f53f-4d2c-b1c3-c90aba33dfaf.png">

**Subtasks**
- [ ] Investigate why addresses from this memory region are in stack traces.
- [ ] Try to understand if some particular part of our `casgstatus` probe is responsible (i.e. because other uprobes do not appear in stack traces).
- [ ] Evaluate perf of go apps with and without our uprobes.
- [ ] Try to reproduce this kind of a stack trace with a targeted/hand-crafted uprobe (either in go, or C/C++).
