### ISSUE TITLE
Change artifact_tracker to use manifest files to track artifacts instead of the Postgres DB

### ISSUE THREAD

**Issue by vihangm** [pixie-io/pixie#864]
**Describe the feature/change**
The available artifacts for `vizier`, `operator`, and the `cli` are currently tracked in the Postgres DB and `artifact_tracker`
queries the DB to list and get artifacts.
The DB needs to be manually updated when new artifacts are released or in the case for a self hosted cloud, we bypass the DB and use hardcoded flags to only return one possible artifact version. The latter scenario is somewhat of a maintenance burden for the Pixie maintainers since we need to remember to update the flags and also a non-ideal setup for self hosted cloud since they only have one pinned version of any artifact available.

We should populate a cloud manifest file with all available and use a job to fetch these manifests and store them as a config map when deploying cloud. Using cluster based configmap ensures that we don't have to constant refetch artifacts and also ensures that if someone running cloud doesn't update cloud, they don't get too new a version of vizier that might not be compatible with their cloud.

**Subtasks**
The list of concrete tasks which must be done to complete this story. These may be low-level and engineering-oriented.

- [ ] Update versions_gen to sort manifests by semver.
- [ ] Add a job to fetch manifests when deploying cloud and write them to a configmap.
- [ ] Update artifact tracker to use configmap to list and get artifacts.

**Comment by JamesMBartlett** [comment]
This was fixed by a series of PRs ending with #1147
